// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 4
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){



var za=this,Aa=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ba=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ca=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Da=function(a){if(null==a)return String(a);var b=Ca.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ea=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ma=function(a){if(!a||"object"!=Da(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ea(a,"constructor")&&!Ea(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ea(a,b)},Fa=function(a,b){var c=b||("array"==Da(a)?[]:{}),d;for(d in a)if(Ea(a,d)){var e=a[d];"array"==Da(e)?("array"!=Da(c[d])&&(c[d]=[]),c[d]=Fa(e,c[d])):ma(e)?(ma(c[d])||(c[d]={}),c[d]=Fa(e,c[d])):c[d]=e}return c};var qa=null,Ha=Math.random(),Ia=null,Ja=null,Ka={},La={};var Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Wa,Xa,Ya,R,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,mb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Jb,Kb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,S,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,nd,od,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,
be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We;
(function(){var a=function(a){return{toString:function(){return a}}};Ma=a("");Na=a("");Oa="";Pa=a("");Qa=a("");Ra=a("");Sa=a("");Ta=a("");Ua=a("");Wa=a("");Xa=a("");Ya=a("0");R=a("1");Za=a("");$a=a("");ab=a("");
bb=a("");cb=a("");db=a("");eb=a("");fb=a("");gb=a("");hb=a("");ib=a("");jb=a("");kb=a("");mb=a("");ob=a("");pb=a("");qb=a("");
rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");yb=a("2");zb=a("");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Jb=a("");
Kb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");
bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");
rc=a("");sc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("3");Ec=a("");Fc=a("12");Gc=a("13");Hc=a("");Ic=a("");
Jc=a("4");S=a("5");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("6");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("7");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");
bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");nd=a("");od=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");
zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");
Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");
he=a("9");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");
ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe="";Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("10");
Pe=a("");Qe=a("");Re=a("11");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("")})();var Xe=function(){},L=function(a){return"function"==typeof a},U=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Ye=function(a){return"number"==Da(a)&&!isNaN(a)},Ze=function(a){return/^[0-9]+$/.test(a)},$e=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},af=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},M=function(a){return Math.round(Number(a))||0},oa=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},bf=function(a){var b=[];if(U(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},cf=function(a,b){if(!Ye(a)||!Ye(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},df=function(){this.prefix="gtm.";this.values={}};df.prototype.set=function(a,b){this.values[this.prefix+a]=b};df.prototype.get=function(a){return this.values[this.prefix+a]};df.prototype.contains=function(a){return void 0!==this.get(a)};
var ef=function(a,b,c){try{if(!a[dd])return a[Dc](a,b||Xe,c||Xe);c&&c()}catch(d){}return!1},ff=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=af(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},gf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},hf=function(a){return function(){return a("GTM-WZL83C")}},jf=function(a){for(var b=0;b<a.length;b++)a[b]()},ja=K().getTime(),na=function(a,
b,c){return a&&a.hasOwnProperty(b)?a[b]:c},kf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},lf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},la=function(a,b,c){if(!(b&&c&&lf(a)&&U(a)&&0!=a.length))return null;for(var d={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(c)&&(d[a[e][b]]=a[e][c]);return d},mf=function(a,b){0==b?a.Ra=!0:a.complete=!0;var c=a.g;a.o&&(a.o.Ea[c]=b);Ka[c]&&(Ka[c].state=b)},nf=function(a,b){a.sort(function(a,
d){return b(a,d)?-1:b(d,a)?1:0})};var C=window,Q=document,qf=navigator,J=function(a,b,c){var d=C[a];C[a]=void 0===d||c?b:d;return C[a]},O=function(a,b,c,d){return(d||"http:"!=C.location.protocol?a:b)+c},rf=function(a){var b=Q.getElementsByTagName("script")[0]||Q.body||Q.head;b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},p=function(a,b,c){var d=Q.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;pa(d,b);c&&(d.onerror=c);rf(d)},ha=function(a,b){var c=Q.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";rf(c);pa(c,b);void 0!==a&&(c.src=a);return c},z=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},V=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},r=function(a){C.setTimeout(a,0)},sa=!1,
ua=[],sf=function(a){if(!sa){var b=Q.createEventObject,c="complete"==Q.readyState,d="interactive"==Q.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){sa=!0;for(var e=0;e<ua.length;e++)ua[e]()}ua.push=function(){for(var a=0;a<arguments.length;a++)r(arguments[a]);return 0}}},tf=0,uf=function(){if(!sa&&140>tf){tf++;try{Q.documentElement.doScroll("left"),sf()}catch(a){C.setTimeout(uf,50)}}},Cf=function(a){var b=Q.getElementById(a);if(b&&Bf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Bf(document.all[a][c],
"id")==a)return document.all[a][c];return b},Bf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Df=function(a){return a.target||a.srcElement||{}},xa=function(a){var b=Q.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Ef=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Ff=!1,Gf=[],Hf=function(){if(!Ff){Ff=!0;for(var a=0;a<Gf.length;a++)Gf[a]()}},If=function(a){a=a||C;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},va=function(a){window.console&&window.console.log&&window.console.log(a)};var Jf=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||C.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||C.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:C.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=$e(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Kf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ya=function(a){var b=Q.createElement("a");
a&&(b.href=a);return b};var fa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Jf(ya(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};var ea=function(a,b,c){p(a,b,c)},u=C,aa=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]},ba=function(a,b,c){return("https:"==C.location.protocol?a:b)+c};var Lf=new df,Mf={},Of={set:function(a,b){Fa(Nf(a,b),Mf)},get:function(a){return I(a,2)},reset:function(){Lf=new df;Mf={}}},I=function(a,b){if(2==b){for(var c=Mf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Lf.get(a)},Nf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Pf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Qf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Rf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Sf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Tf=function(){var a=I("gtm.whitelist");
var b=a&&Sf(bf(a),Qf),c=I("gtm.blacklist")||I("tagTypeBlacklist")||[];Pf.test(C.location&&C.location.hostname)&&(c=bf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Sf(bf(c),Rf),e={};return function(f){var g=f&&f[Dc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>$e(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>$e(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=$e(d,g.a)))a:{for(var n=g.b||[],q=new df,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<n.length;t++)if(q.get(n[t])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var of=function(a){var b=Q;return Uf?b.querySelectorAll(a):null},Vf=!1;if(Q.querySelectorAll)try{var Wf=Q.querySelectorAll(":root");Wf&&1==Wf.length&&Wf[0]==Q.documentElement&&(Vf=!0)}catch(a){}var Uf=Vf;var _eu=function(a){var b=String(I("gtm.elementUrl")||a[Zb]||""),c=ya(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ja};_e.a="e";_e.b=["google"];var ag=/(^|\.)doubleclick\.net$/i,bg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,cg=function(a){for(var b=String(Q.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=af(e[0]);if(f&&f==a){var g=af(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},dg=function(a,b,c,d,e){if(ag.test(Q.location.hostname)||"/"==c&&bg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=Q.cookie;Q.cookie=f;return g!=
Q.cookie||0<=$e(cg(a),b)},eg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},fg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},gg=function(){var a=Jf(C.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var hg=function(a,b){this.f=a;this.i=b};hg.prototype.toString=function(){var a=""+this.f;1<this.i&&(a=a+"-"+this.i);return a};var ig=function(a,b){this.Ca=a;this.da=b};ig.prototype.toString=function(){return""+this.da+"."+this.Ca};var lg=function(a,b){var c=new jg(null,a,b);kg(c);return c},jg=function(a,b,c){this.Ka=Math.floor(K().getTime()/864E5);this.ca=b||"auto";this.U=c||"/";var d=eg(this.ca),e=fg(this.U);this.C=a||new hg(d,e);this.h=[];this.A=new df},ng=function(a,b,c){b&&(""==c.Ca?mg(a,b):(a.A.contains(b)||a.h.push(b),a.A.set(b,c)))},og=function(a,b){for(var c=0;c<b.length;c++)ng(a,b[c][0],b[c][1])},mg=function(a,b){var c=$e(a.h,b);0<=c&&a.h.splice(c,1);a.A.set(b,void 0)},pg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.A.get(d)])}return b},qg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.A.get(a.h[c]).da);return 864E5*b};jg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.A.get(c).toString())}return"GAX1."+this.C.toString()+"."+a.join("!")};
var rg=function(a,b){for(var c=new Date,d=fg(a.U),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.A.get(g).da<a.Ka&&e.push(g)}for(f=0;f<e.length;f++)mg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(qg(a));if("auto"!=a.ca)return dg("_gaexp",a.toString(),a.U,a.ca,c);for(var h=gg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.C=new hg(eg(h[k]),d),dg("_gaexp",a.toString(),a.U,h[k],c)))return!0;return!1},kg=function(a){for(var b=a.C.f,c=a.C.i,d=cg("_gaexp"),e=[],f=0;f<d.length;f++){var g=sg(a,d[f]);g&&e.push(g)}nf(e,
function(a,d){var e=a.C,f=d.C;return e.f==f.f&&e.i==f.i?!1:e.f==b&&e.i==c?!0:f.f==b&&f.i==c?!1:e.f==b?f.f!=b||e.i<f.i:f.f==b?!1:e.i==c?f.f!=b&&(f.i!=c||e.f<f.f):f.i==c?!1:e.f<f.f||e.f==f.f&&e.i<f.i});a.C=0<e.length?e[0].C:new hg(b,c);for(f=e.length-1;0<=f;f--)og(a,pg(e[f]))},sg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=af(e[0]);if(0!=f.length){var g=2==e.length?af(e[1]):"1";if(Ze(f)&&Ze(g)){d=new hg(M(f),M(g));
break a}}}d=void 0}if(d){for(var h=new jg(d,a.ca,a.U),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!Ze(l[1]))return;ng(h,l[0],new ig(l[2],M(l[1])))}}return h}}};var _f=function(a){var b=String(I("gtm.referrer")||Q.referrer);if(!b)return b;var c=ya(b);return b};_f.a="f";_f.b=["google"];var ia=function(a){var b=C.location,c;(c=a[Ob]?a[Ob]:I("gtm.url"))&&(b=ya(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[yb]&&(f=Jf(b,a[yb],a[be],a[Yb],a[Pd]));return f},_u=ia;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Ya])==String(a[R])};_eq.a="eq";_eq.b=["google"];
var Cg=!1,Dg=[],Eg=function(a){var b=C.google_trackConversion,c=a.gtm_onFailure;L(b)?b(a)||c():c()},Fg=function(){for(;0<Dg.length;)Eg(Dg.shift())},_awct=function(a,b,c){var d={google_conversion_id:a[S],google_conversion_label:a[Uc],google_conversion_value:a[Re]||0,google_remarketing_only:!1,onload_callback:b,gtm_onFailure:c};a[Nb]&&(d.google_conversion_currency=a[Nb]);a[xd]&&(d.google_conversion_order_id=a[xd]);Dg.push(d);Cg||(Cg=!0,p("//www.googleadservices.com/pagead/conversion_async.js",function(){Fg();
Dg={push:Eg}},function(){Fg();Cg=!1}))};_awct.a="awct";_awct.b=["google"];var Gg=Math.random(),Hg="1.000000">Gg;var Ig=Xe;var Jg=Xe,Kg=[],Lg=!1,Mg=function(a){return C["dataLayer"].push(a)},Ng=function(a){var b=!1;return function(){!b&&L(a)&&r(hf(a));b=!0}},Tg=function(){for(var a=!1;!Lg&&0<Kg.length;){Lg=!0;var b=Kg.shift();if(L(b))try{b.call(Of)}catch(ta){}else if(U(b))a:{var c=b;if("string"==Da(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Mf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(ta){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,n=
k[m];Lf.set(l,n);Fa(Nf(l,n),Mf)}var q=!1,t=k.event,v=void 0;if(t){v=ja++;Ja=t;if(!k["gtm.uniqueEventId"]){var w=v;Lf.set("gtm.uniqueEventId",w);Fa(Nf("gtm.uniqueEventId",w),Mf)}var A=Ng(k.eventCallback),E=k.eventTimeout;E&&C.setTimeout(A,Number(E));q=Jg(v,t,A,k.eventReporter)}Ia||(Ia=k["gtm.start"])&&Ig();var F=k,D=v,y=t,G=Mf;if(!q){var B=v,H=t;}Ja=null;a=q||a}var P=b,N=Mf;Sg();Lg=!1}return!a},Ug=function(){var a=Tg();try{var b=C["dataLayer"].hide;if(b&&void 0!==b["GTM-WZL83C"]&&b.end){b["GTM-WZL83C"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a};var Vg,Wg,Xg,Yg=/(Firefox\D28\D)/g.test(qf.userAgent),dh=function(a,b){return function(c){c=c||C.event;var d=Df(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Ef(d,["a","area"]),e=!d||!d.href||Zg(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Xg:Wg;if(c.defaultPrevented||!1===c.returnValue||c.qa&&c.qa()){if(d){var g={simulateDefault:!1},h=$g(f,["wnc","nwnc"]);h&&ah(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=$g(f,
["wnc","nwnc","nwc","wc"]);(k=ah(a,d,g,f.wt,m))||(bh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Yg;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=ch(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},ah=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Bf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=eh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=fh(b);g.eventTimeout=f;g.eventCallback=gh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Mg(g)},
fh=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},hh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},ch=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(qf.userAgent),e=hh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=C.frames&&C.frames[f]||C[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+K().getTime(),b.targetWindow=C.open("",b.targetWindowName));break;default:d&&!C.frames[e]?(b.simulateDefault=!1,c=!0):(C.frames[e]||(b.targetWindowName=e),b.targetWindow=C.frames[e]||C.open("",e))}return c},eh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&C.setTimeout(eh(a,b,c),25)))}},gh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);Q.gtmSubmitFormNow=!0;ih(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&C.setTimeout(gh(a,b,c),25)}},$g=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},jh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},bh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<kh.length;c++)if(a.passingRules[c]){var d=kh[c],e=lh[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},mh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(Q.gtmHasClickListenerTag)return;Q.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Df(a);b&&ah("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Vg&&(Vg=Kf(Q.location));jh(Wg,b||!1,c||!1,d,e);if(Q.gtmHasLinkClickListenerTag)return;
Q.gtmHasLinkClickListenerTag=!0;f="click";g=dh(a,b||!1);break;case "FORM_SUBMIT":jh(Xg,b||!1,c||!1,d,e);if(Q.gtmHasFormSubmitListenerTag)return;Q.gtmHasFormSubmitListenerTag=!0;f="submit";g=dh(a,b||!1);break;default:return}V(Q,f,g,h)},Zg=function(a){if(!Vg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ya(a);return Vg==Kf(c)},ih=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
Q.gtmFormElementSubmitter||(Q.gtmFormElementSubmitter=Q.createElement("form"));return Q.gtmFormElementSubmitter.submit.call?Q.gtmFormElementSubmitter.submit:a.submit};var tg=new String("undefined"),uh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===tg?b:a[d]);return c.join("")}};uh.prototype.toString=function(){return this.resolve("undefined")};uh.prototype.valueOf=uh.prototype.toString;var vh={},wh=function(a,b){var c=ja++;vh[c]=[a,b];return c},xh=function(a){var b=a?0:1;return function(a){var d=vh[a];if(d&&L(d[b]))d[b]();vh[a]=void 0}};var yh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},zh=function(a,b){return a<b?-1:a>b?1:0};var Ah;a:{var Bh=za.navigator;if(Bh){var Ch=Bh.userAgent;if(Ch){Ah=Ch;break a}}Ah=""}var W=function(a){return-1!=Ah.indexOf(a)};var Dh=W("Opera"),Eh=W("Trident")||W("MSIE"),Fh=W("Edge"),Gh;if(Gh=W("Gecko"))Gh=!(-1!=Ah.toLowerCase().indexOf("webkit")&&!W("Edge"));var Hh=Gh&&!(W("Trident")||W("MSIE"))&&!W("Edge"),Ih=-1!=Ah.toLowerCase().indexOf("webkit")&&!W("Edge");Ih&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var Jh=za.navigator||null;Jh&&(Jh.appVersion||"").indexOf("X11");W("Android");!W("iPhone")||W("iPod")||W("iPad");W("iPad");W("iPod");
var Kh=function(){var a=za.document;return a?a.documentMode:void 0},Lh;a:{var Mh="",Nh=function(){var a=Ah;if(Hh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Fh)return/Edge\/([\d\.]+)/.exec(a);if(Eh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ih)return/WebKit\/(\S+)/.exec(a);if(Dh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Nh&&(Mh=Nh?Nh[1]:"");if(Eh){var Oh=Kh();if(null!=Oh&&Oh>parseFloat(Mh)){Lh=String(Oh);break a}}Lh=Mh}
var Ph=Lh,Qh={},Rh=function(a){var b;if(!(b=Qh[a])){for(var c=0,d=yh(String(Ph)).split("."),e=yh(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],q=l.exec(k)||["","",""];if(0==n[0].length&&0==q[0].length)break;c=zh(0==n[1].length?0:parseInt(n[1],10),0==q[1].length?0:parseInt(q[1],10))||zh(0==n[2].length,0==q[2].length)||zh(n[2],q[2])}while(0==c)}b=Qh[a]=0<=c}return b},
Sh=za.document,Th=Sh&&Eh?Kh()||("CSS1Compat"==Sh.compatMode?parseInt(Ph,10):5):void 0;var Uh;if(!(Uh=!Hh&&!Eh)){var Vh;if(Vh=Eh)Vh=9<=Number(Th);Uh=Vh}Uh||Hh&&Rh("1.9.1");Eh&&Rh("9");var Wh=function(a){Wh[" "](a);return a};Wh[" "]=function(){};var wa=function(a,b){var c="";Eh&&!Xh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Yh)a.srcdoc=d;else if(Zh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else $h(a,d)},Yh=Ih&&"srcdoc"in document.createElement("iframe"),Zh=Hh||Ih||Eh&&Rh(11),$h=function(a,b){Eh&&Rh(7)&&!Rh(10)&&6>ai()&&bi(b)&&(b=ci(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Eh&&!Xh(a)?di(a,c):c()},ai=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Xh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Wh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},ei=0,di=function(a,b){var c="goog_rendering_callback"+ei++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},bi=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},ci=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var fi,ra=function(){};(function(){function a(a,g){a=a||"";g=g||{};for(var m in b)b.hasOwnProperty(m)&&(g.$a&&(g["fix_"+m]=!0),g.Ma=g.Ma||g["fix_"+m]);var l={comment:/^\x3c!--/,endTag:/^<\//,atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,startTag:/^</,chars:/^[^<]/},n={comment:function(){var b=a.indexOf("--\x3e");if(0<=b)return{content:a.substr(4,b),length:b+3}},endTag:function(){var b=a.match(d);if(b)return{tagName:b[1],length:b[0].length}},atomicTag:function(){var b=n.startTag();
if(b){var c=a.slice(b.length);if(c.match(new RegExp("</\\s*"+b.tagName+"\\s*>","i"))){var d=c.match(new RegExp("([\\s\\S]*?)</\\s*"+b.tagName+"\\s*>","i"));if(d)return{tagName:b.tagName,j:b.j,content:d[1],length:d[0].length+b.length}}}},startTag:function(){var b=a.match(c);if(b){var d={};b[2].replace(e,function(a,b,c,e,g){var h=c||e||g||f.test(b)&&b||null,k=document.createElement("div");k.innerHTML=h;d[b]=k.textContent||k.innerText||h});return{tagName:b[1],j:d,X:!!b[3],length:b[0].length}}},chars:function(){var b=
a.indexOf("<");return{length:0<=b?b:a.length}}},q=function(){for(var b in l)if(l[b].test(a)){var c=n[b]();return c?(c.type=c.type||b,c.text=a.substr(0,c.length),a=a.slice(c.length),c):null}};g.Ma&&function(){var b=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i,c=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i,d=[];d.Na=function(){return this[this.length-1]};d.sa=function(a){var b=this.Na();return b&&b.tagName&&b.tagName.toUpperCase()===a.toUpperCase()};d.jb=
function(a){for(var b=0,c;c=this[b];b++)if(c.tagName===a)return!0;return!1};var e=function(a){a&&"startTag"===a.type&&(a.X=b.test(a.tagName)||a.X);return a},f=q,l=function(){a="</"+d.pop().tagName+">"+a},m={startTag:function(b){var e=b.tagName;"TR"===e.toUpperCase()&&d.sa("TABLE")?(a="<TBODY>"+a,n()):g.Sb&&c.test(e)&&d.jb(e)?d.sa(e)?l():(a="</"+b.tagName+">"+a,n()):b.X||d.push(b)},endTag:function(a){d.Na()?g.lb&&!d.sa(a.tagName)?l():d.pop():g.lb&&(f(),n())}},n=function(){var b=a,c=e(f());a=b;if(c&&
m[c.type])m[c.type](c)};q=function(){n();return e(f())}}();return{append:function(b){a+=b},vb:q,Wb:function(a){for(var b;(b=q())&&(!a[b.type]||!1!==a[b.type](b)););},clear:function(){var b=a;a="";return b},Xb:function(){return a},stack:[]}}var b=function(){var a={},b=this.document.createElement("div");b.innerHTML="<P><I></P></I>";a.$b="<P><I></P></I>"!==b.innerHTML;b.innerHTML="<P><i><P></P></i></P>";a.Yb=2===b.childNodes.length;return a}(),c=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
d=/^<\/([\-A-Za-z0-9_]+)[^>]*>/,e=/([\-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,f=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;a.supports=b;a.ac=function(a){var b={comment:function(a){return"<--"+a.content+"--\x3e"},endTag:function(a){return"</"+a.tagName+">"},atomicTag:function(a){return b.startTag(a)+a.content+b.endTag(a)},startTag:function(a){var b="<"+a.tagName,c;for(c in a.j)var d=a.j[c],
b=b+(" "+c+'="'+(d?d.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"');return b+(a.X?"/>":">")},chars:function(a){return a.text}};return b[a.type](a)};a.Rb=function(a){var b={},c;for(c in a){var d=a[c];b[c]=d&&d.replace(/(^|[^\\])"/g,'$1\\"')}return b};for(var g in b)a.eb=a.eb||!b[g]&&g;fi=a})();(function(){function a(){}function b(a){return void 0!==a&&null!==a}function c(a,b){var c,d=a&&a.length||0;for(c=0;c<d;c++)b.call(void 0,a[c],c)}function d(a,b){for(var c in a)a.hasOwnProperty(c)&&b.call(void 0,c,a[c])}
function e(a,b){d(b,function(b,c){a[b]=c});return a}function f(a,c){a=a||{};d(c,function(c,d){b(a[c])||(a[c]=d)});return a}function g(a){try{return m.call(a)}catch(b){var d=[];c(a,function(a){d.push(a)});return d}}var h={Va:a,Wa:a,Xa:a,Ya:a,ab:a,bb:function(a){return a},done:a,error:function(a){throw a;},wb:!1},k=this;if(!k.ia){var m=Array.prototype.slice,l=function(){function a(c,d,e){var f="data-ps-"+d;if(2===arguments.length){var g=c.getAttribute(f);return b(g)?String(g):g}b(e)&&""!==e?c.setAttribute(f,
e):c.removeAttribute(f)}function f(b,c){var d=b.ownerDocument;e(this,{root:b,options:c,Y:d.defaultView||d.parentWindow,J:d,ha:fi("",{$a:!0}),na:[b],ya:"",za:d.createElement(b.nodeName),V:[],I:[]});a(this.za,"proxyof",0)}f.prototype.write=function(){[].push.apply(this.I,arguments);for(var a;!this.ba&&this.I.length;)a=this.I.shift(),"function"===typeof a?this.ib(a):this.Ha(a)};f.prototype.ib=function(a){var b={type:"function",value:a.name||a.toString()};this.xa(b);a.call(this.Y,this.J);this.Oa(b)};
f.prototype.Ha=function(a){this.ha.append(a);for(var b,c=[],d,e;(b=this.ha.vb())&&!(d=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("script"):!1)&&!(e=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("style"):!1);)c.push(b);this.Db(c);d&&this.mb(b);e&&this.nb(b)};f.prototype.Db=function(a){var b=this.fb(a);b.Ia&&(b.ob=this.ya+b.Ia,this.ya+=b.ub,this.za.innerHTML=b.ob,this.Bb())};f.prototype.fb=function(a){var b=this.na.length,d=[],e=[],f=[];c(a,function(a){d.push(a.text);if(a.j){if(!/^noscript$/i.test(a.tagName)){var c=
b++;e.push(a.text.replace(/(\/?>)/," data-ps-id="+c+" $1"));"ps-script"!==a.j.id&&"ps-style"!==a.j.id&&f.push("atomicTag"===a.type?"":"<"+a.tagName+" data-ps-proxyof="+c+(a.X?" />":">"))}}else e.push(a.text),f.push("endTag"===a.type?a.text:"")});return{Ga:a,raw:d.join(""),Ia:e.join(""),ub:f.join("")}};f.prototype.Bb=function(){for(var c,d=[this.za];b(c=d.shift());){var e=1===c.nodeType;if(!e||!a(c,"proxyof")){e&&(this.na[a(c,"id")]=c,a(c,"id",null));var f=c.parentNode&&a(c.parentNode,"proxyof");f&&
this.na[f].appendChild(c)}d.unshift.apply(d,g(c.childNodes))}};f.prototype.mb=function(a){var b=this.ha.clear();b&&this.I.unshift(b);a.src=a.j.src||a.j.Jb;a.src&&this.V.length?this.ba=a:this.xa(a);var c=this;this.Cb(a,function(){c.Oa(a)})};f.prototype.nb=function(a){var b=this.ha.clear();b&&this.I.unshift(b);a.type=a.j.type||a.j.Nb||"text/css";this.Eb(a);b&&this.write()};f.prototype.Eb=function(a){var b=this.hb(a);this.qb(b);a.content&&(b.styleSheet&&!b.sheet?b.styleSheet.cssText=a.content:b.appendChild(this.J.createTextNode(a.content)))};
f.prototype.hb=function(a){var b=this.J.createElement(a.tagName);b.setAttribute("type",a.type);d(a.j,function(a,c){b.setAttribute(a,c)});return b};f.prototype.qb=function(a){this.Ha('<span id="ps-style"/>');var b=this.J.getElementById("ps-style");b.parentNode.replaceChild(a,b)};f.prototype.xa=function(a){a.tb=this.I;this.I=[];this.V.unshift(a)};f.prototype.Oa=function(a){a!==this.V[0]?this.options.error({message:"Bad script nesting or script finished twice"}):(this.V.shift(),this.write.apply(this,
a.tb),!this.V.length&&this.ba&&(this.xa(this.ba),this.ba=null))};f.prototype.Cb=function(a,b){var c=this.gb(a),d=this.yb(c),e=this.options.Va;a.src&&(c.src=a.src,this.xb(c,d?e:function(){b();e()}));try{this.pb(c),a.src&&!d||b()}catch(f){this.options.error(f),b()}};f.prototype.gb=function(a){var b=this.J.createElement(a.tagName);d(a.j,function(a,c){b.setAttribute(a,c)});a.content&&(b.text=a.content);return b};f.prototype.pb=function(a){this.Ha('<span id="ps-script"/>');var b=this.J.getElementById("ps-script");
b.parentNode.replaceChild(a,b)};f.prototype.xb=function(a,b){function c(){a=a.onload=a.onreadystatechange=a.onerror=null}var d=this.options.error;e(a,{onload:function(){c();b()},onreadystatechange:function(){/^(loaded|complete)$/.test(a.readyState)&&(c(),b())},onerror:function(){var e={message:"remote script failed "+a.src};c();d(e);b()}})};f.prototype.yb=function(a){return!/^script$/i.test(a.nodeName)||!!(this.options.wb&&a.src&&a.hasAttribute("async"))};return f}();k.ia=function(){function b(){var a=
m.shift(),d;a&&(d=a[a.length-1],d.Wa(),a.stream=c.apply(null,a),d.Xa())}function c(f,h,k){function m(a){a=k.bb(a);w.write(a);k.Ya(a)}w=new l(f,k);w.id=d++;w.name=k.name||w.id;var q=f.ownerDocument,v={close:q.close,open:q.open,write:q.write,writeln:q.writeln};e(q,{close:a,open:a,write:function(){return m(g(arguments).join(""))},writeln:function(){return m(g(arguments).join("")+"\n")}});var x=w.Y.onerror||a;w.Y.onerror=function(a,b,c){k.error({Ub:a+" - "+b+":"+c});x.apply(w.Y,arguments)};w.write(h,
function(){e(q,v);w.Y.onerror=x;k.done();w=null;b()});return w}var d=0,m=[],w=null;return e(function(c,d,e){"function"===typeof e&&(e={done:e});e=f(e,h);c=/^#/.test(c)?k.document.getElementById(c.substr(1)):c.Tb?c[0]:c;var g=[c,d,e];c.ia={cancel:function(){g.stream?g.stream.abort():g[1]=a}};e.ab(g);m.push(g);w||b();return c.ia},{Zb:{},Vb:m,Ob:l})}();ra=k.ia}})();
var gi=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=gi(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=Q.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,pa(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);gi(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){r(d)}}};var hi=function(a,b,c){var d=function(){var d=qa;d.postscribe||(d.postscribe=ra);var f={done:b},g=Q.createElement("div");g.style.display="none";g.style.visibility="hidden";Q.body.appendChild(g);try{d.postscribe(g,a,f)}catch(h){r(c)}};sa?d():ua.push(d)};var ii=function(a,b,c){if(Q.body){var d=
a[Jc];d instanceof uh&&(d=d.resolve(wh(b,c)),b=Xe);if(a[Me])try{wa(ha(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),r(b)}catch(e){r(c)}else a[Oe]?hi(d,b,c):gi(Q.body,xa(d),b,c)()}else C.setTimeout(function(){ii(a,b,c)},200)},_html=ii;_html.a="html";_html.b=["customScripts"];
var ui=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=ri(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=si(a+"{"+e+"}",f);ti(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},vi=null,ri=function(a){if(vi)return vi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return vi=c}0==a.styleSheets.length&&
a.createStyleSheet();return vi=a.styleSheets[0]},si=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},ti=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Ci={},Di=void 0,Ei=function(a){var b=Ci[a];b||(b={id:a,s:[],R:0,Fa:null,wa:void 0,Aa:!1},Ci[a]=b);Di=b},Gi=function(a,b,c,d){var e=Di;if(!Uf||!e)return!1;var f={id:e.id+":"+e.s.length,Za:b,O:[],Ua:c,D:a,oa:0,ma:d||null,Ja:0,P:!1};e.s.push(f);null===a?(f.P=!0,b(null)):Fi(e);return!0},Hi=function(a){var b=ui(a,"visibility","hidden",!0);return function(){L(b)&&b.apply();b=null}},Ii=function(a,b,c,d){var e=b;if(!sa){var f=Hi(a.v);ua.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Gi(a,e,
c,d)},Fi=function(a){if(!a.Aa){for(var b=a.R;b<a.s.length;b++){var c=a.s[b],d=b==a.R;if(!c.P&&!Ji(d,c))break;c.P&&d&&a.R++}a.s.length>a.R?(a.Fa||(a.Fa=C.setTimeout(function(){a.Fa=null;Fi(a)},80)),sa||a.wa||(a.wa=function(){r(function(){Fi(a)})},V(Q,"DOMContentLoaded",a.wa))):Ki(a)}},Ki=function(a){for(var b=0;b<a.s.length;b++){var c=a.s[b];if(c.D)for(var d=of(c.D.v)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Li(f,c.id),c.O.push(Mi(f,c.id)))}}},Ji=
function(a,b){var c=[];if(b.D){var d=Ni(b.D,b.id),e=null;b.ma&&(e=Ni(b.ma,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!sa&&(null===b.ma.m||b.Ja+c.length<b.ma.m)))break;c.push({element:g,zb:h})}}if(!sa&&b.Ua&&(!a||null==b.D.m||b.D.m!=b.oa+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].zb,n;b.oa++;Li(m,b.id);l&&(b.Ja++,n=b.id+"-t",Li(l,n));var q=b.Za(m,l);L(q)&&b.O.push(q);b.O.push(Mi(m,b.id));l&&n&&b.O.push(Mi(l,n))}if(b.D.m&&
b.D.m==b.oa||sa)b.P=!0;return!0},Li=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Mi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ni=function(a,b){for(var c=of(a.v)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.B&&!Oi(f))break;d.push(f)}}return d},Oi=function(a){if(sa)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ri,Si;var bj=function(a){return function(){}},cj=function(a){return function(){}};var Fj=function(a){var b=C||za,c=b.onerror,d=!1;Ih&&!Rh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,sb:g,Pb:h,error:k});return d}};var bk=28,ck=[],dk=[],ek=[],fk=new df,gk=[],Z=[],kh=[],lh=[],hk=function(){this.G=[]};hk.prototype.set=function(a,b){this.G.push([a,b]);return this};hk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.G.length;d++){var e=ik(this.G[d][0],a,b),f=ik(this.G[d][1],a,b);c[e]=f}return c};var jk=function(a){this.index=a};jk.prototype.resolve=function(a,b){var c=ek[this.index];if(c&&!b(c)){var d=c[Oc];if(a){if(a.get(d))return;a.set(d,!0)}c=ik(c,a,b);a&&a.set(d,!1);return ef(c)}};
var _M=function(a){return new jk(a)},kk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=ik(ck[a[f]],b,c);g===tg&&(e=!0);d.push(g)}return e?new uh(d):d.join("")}},_T=function(a){return new kk(arguments)},lk=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=ik(a[0],c,d);if(a[0]instanceof jk&&b(8)&&b(16)){if(e===tg)return e;var f="gtm"+ja++;fk.set(f,e);return'google_tag_manager["GTM-WZL83C"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new lk(arguments)},mk=function(a,b){this.u=a;this.la=b},_R=function(a,b){return new mk(a,b)},nk=function(a,b){return ik(a,new df,b)},ik=function(a,b,c){var d=a;if(a instanceof jk||a instanceof hk||a instanceof kk||a instanceof lk)return a.resolve(b,
c);if(!(a instanceof mk))if(U(a))for(var d=[],e=0;e<a.length;e++)d[e]=ik(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=ik(a[f],b,c))}return d},ok=function(a,b){var c=b[a],d=c;if(c instanceof jk||c instanceof lk||c instanceof kk||c instanceof mk)d=c;else if(U(c))for(var d=[],e=0;e<c.length;e++)d[e]=ok(c[e],b);else if("object"==typeof c){var d=new hk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],ok(c[f],b))}return d},qk=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=ck[e[1]]);if(1==a)for(var f=pk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=dk[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=pk(e[g]);3==a&&(c[d]=ck[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=ck[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},pk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<bk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},rk=function(a,b,c){a.push.apply(a,qk(b,c))};
var Pg=function(){},zk=function(a){},Sg=function(){},Ak=function(a){},Bk=function(a,b){},Ck=function(a,b){},Qg=function(a){};var Dk=function(a){var b=this;this.g=a;this.complete=this.Ra=!1;this.ka=[];this.ea=[];this.M=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||jf(b.ka);mf(b,1);if(La[a])for(var e=0;e<La[a].length;e++)La[a].shift().M()};this.L=function(){if(b.o&&b.o.event){var c=b.o.event,d=b.g;}b.complete||
jf(b.ea);mf(b,2);if(La[a])for(var e=0;e<La[a].length;e++)La[a].shift().L()};this.w=Xe},Ek=function(a,b){a.ka.push(b)},Fk=function(a,b){a.ea.push(b)},Gk=function(a){this.H=[];this.Da=[];this.La={};this.ua=[];this.S=0;this.Pa={};this.Sa={};this.Ea={};this.event=a};Gk.prototype.addListener=function(a){this.ua.push(a)};
var Hk=function(a,b,c,d,e,f){if(!c.complete){a.H[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=U(d)?d.slice():["or",d];e=U(e)?e.slice():[e];f=U(f)?f.slice():[f];a.La[b]=d;a.Pa[b]=0<e.length;a.Sa[b]=0<f.length;a.S++;var g=function(){0<a.S&&a.S--;0<a.S||jf(a.ua)};Ek(c,g);Fk(c,g)}},Ik=function(a,b,c){a.H[b]&&(Ek(a.H[b],function(){c(b,!0)}),Fk(a.H[b],function(){c(b,!1)}))},Jk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof mk&&a[g].u===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Nk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Kk(h,b,a);if(f=g){var k=Lk(b,!0);0<k.length&&e(k[0].u);c.push(f);var l=Lk(b,!1);0<l.length&&e(l[0].u)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Lk(g.g,!0);if(0<h.length){var k=c[f-1],m=Mk(g);Ek(k,m);0==h[0].la&&Fk(k,m)}var l=Lk(g.g,!1);0<l.length&&(m=Mk(c[f+1]),Ek(g,m),0==l[0].la&&Fk(g,m))}a.Da.push(c)}},Lk=function(a,b){var c=b?Zd:pe,d=Z[a],e=void 0===d[c]?[]:d[c];return U(e)?e:[e]},Mk=function(a){return function(){a.w()}},Pk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Lk(a,!0);0<b.length&&f(b[0].u);e.push(a);var c=Lk(a,!1);0<c.length&&f(c[0].u)};
f(d.g);b[d.g]=e}Ok(a,b);return b},Ok=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<$e(b[e],d)){delete b[d];break}}};var Rk=function(a,b){return function(){a[Fc]=b.M;a[Gc]=b.L;var c=b.g,d=b.o&&b.o.Ea[c],e=Ka[c]&&Ka[c].state,f=d?void 0!==d:b.Ra||b.Qb,g=Ka[c]&&Ka[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){mf(b,0);var m=b.o?b.o.event:void 0;a=Qk(a,m?m.c:Tf());if(m){var l=a;Bk(m,c)}ef(a,b.M,b.L)}else h&&0==e||k&&0==d?La[c].push(b):h&&1==e||k&&1==d?b.M():b.L()}},Qk=function(a,b){a=nk(a,b);return a},Kk=function(a,b,c){var d=new Dk(b);d.o=c;Ek(d,bj(a));Fk(d,cj(a));d.w=Rk(a,d);return d};var Wk,Xk;var fl=!1;var gl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=gk[b]&&nk(gk[b],c),e=d;if(d)if(d[Xa]&&U(d[R]))for(var f=d[R],e=!1,g=0;!e&&g<f.length;g++)d[R]=f[g],e=ef(d);else e=ef(d);a[b]=[e,d]}return a[b]}},yk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.K(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.K(e[d],a.c)[0])return!1;return!0},hl=!1,Jg=function(a,b,c,d){switch(b){case "gtm.js":if(hl)return!1;hl=!0;break;case "gtm.sync":if(I("gtm.snippet")!=Ha)return!1}I("tagTypeBlacklist");
for(var e={id:a,name:b,aa:c||Xe,Z:pk(),ja:pk(),K:gl(),c:Tf()},f=[],g=0;g<kh.length;g++)if(yk(e,kh[g])){f[g]=!0;for(var h=e,k=kh[g],m=k[1],l=0;l<m.length;l++)h.Z[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ja[n[l]]=!0}else f[g]=!1;Bk(e);var t=[];for(var v=0;v<bk;v++)if(e.Z[v]&&!e.ja[v])if(e.c(Z[v])){}else{t[v]=Z[v];}e.N=t;for(var w=new Gk(e),A=0;A<bk;A++)if(e.Z[A]&&!e.ja[A])if(e.c(Z[A])){}else{var E=e.N[A],F=Kk(E,A,w);Hk(w,A,F,E[$b],E[Zd],E[pe]);if(E[Ma])break}w.addListener(e.aa);for(var D=[],y=
0;y<w.H.length;y++){var G=w.H[y];if(G){var x=w.La[y],B=w.Pa[y],H=w.Sa[y];if(0!=x.length||B||H){if(0<x.length)for(var P=Jk(x,G.w),N=0;N<x.length;N++)x[N]instanceof mk&&x[N].u!=y&&Ik(w,x[N].u,P);(B||H)&&Nk(w,y)}else D.push(y)}}for(y=0;y<D.length;y++)w.H[D[y]].w();for(y=0;y<w.Da.length;y++){for(var ta=w.Da[y],T=ta,ga=[],da=0;da<T.length;da++){var nb=T[da],lb=nb.g,Lb=Ka[lb],pd=Lb.firingOption;0!=pd&&(1==pd&&void 0!==nb.o.Ea[lb]||2==pd&&void 0!==Lb.state)&&ga.push(nb)}var qd=Pk(ga),tc=void 0;for(tc in qd)if(qd.hasOwnProperty(tc)){for(var vf=
void 0,kj=void 0,ld=qd[tc],ul=ld[0],rj=ld[ld.length-1],sj,Ga=0;Ga<T.length;Ga++){var md=T[Ga];!vf&&md.g==ul&&0<Ga&&(vf=T[Ga-1]);md.g==rj&&Ga<T.length-1&&(kj=T[Ga+1]);if(-1<$e(ld,md.g))if(sj=T.splice(Ga,1)[0],md.g==rj)break;else Ga--}if(sj){var tj=Number(tc),ka=vf,wf=kj;if(ka){var vl=ka.ka[0],wl=ka.ea[0],uj=ka;uj.ka=[];uj.ea=[];Ek(ka,vl);Fk(ka,wl)}if(ka&&wf){var xf=Mk(wf);Ek(ka,xf);var yf=Lk(ka.g,!1);0<yf.length&&yf[0].u!=tj&&0==yf[0].la&&Fk(ka,xf);var zf=Lk(wf.g,!0);0<zf.length&&zf[0].u!=tj&&0==zf[0].la&&
Fk(ka,xf)}}}0<ta.length&&ta[0].w()}0<w.S||jf(w.ua);d&&L(d)&&d({passingRules:f,resolvedTags:e.N});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var xj in e.N)if(e.N.hasOwnProperty(xj)){var yj=e.N[xj],Af;if(!(Af=void 0==yj[Oc])){var zj=yj[Oc];Af=!("function"!=typeof String.prototype.startsWith?0===zj.indexOf("_implicit"):zj.startsWith("_implicit"))}if(Af)return!0}return!1};var il={macro:function(a){if(fk.contains(a))return fk.get(a)}};il.dataLayer=Of;il.onHtmlSuccess=xh(!0);il.onHtmlFailure=xh(!1);il.cb=function(){var a=C.google_tag_manager;a||(a=C.google_tag_manager={});a["GTM-WZL83C"]||(a["GTM-WZL83C"]=il);qa=a};(function(){var a=function(a){var c=J("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Wg=a("linkClickMap");Xg=a("formSubmitMap")})();
ck.push.apply(ck,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1974923_2147479553',_awct,true,'956542766','gArBCJHd7GQQrt6OyAM','',3,_html,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(b,e,f,g,a,c,d){b.fbq||(a\x3db.fbq\x3dfunction(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq\x3da),a.push\x3da,a.loaded\x3d!0,a.version\x3d\x222.0\x22,a.queue\x3d[],c\x3de.createElement(f),c.async\x3d!0,c.src\x3dg,d\x3de.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\x22script\x22,\x22//connect.facebook.net/en_US/fbevents.js\x22);fbq(\x22init\x22,\x22417778941754366\x22);fbq(\x22track\x22,\x22PageView\x22);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d417778941754366\x26amp;ev\x3dPageView\x26amp;noscript\x3d1\x22\x3e\x3c/noscript\x3e\n',1,'\n\n\x3cscript type\x3d\x22text/gtmscript\x22\x3evar google_conversion_id\x3d956542766,google_custom_params\x3dwindow.google_tag_params,google_remarketing_only\x3d!0;\x3c/script\x3e\n\x3cscript type\x3d\x22text/gtmscript\x22 data-gtmsrc\x3d\x22//www.googleadservices.com/pagead/conversion.js\x22\x3e\x3c/script\x3e\n\x3cnoscript\x3e\n\x3cdiv style\x3d\x22display:inline;\x22\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22border-style:none;\x22 alt\x3d\x22\x22 src\x3d\x22//googleads.g.doubleclick.net/pagead/viewthroughconversion/956542766/?value\x3d0\x26amp;guid\x3dON\x26amp;script\x3d0\x22\x3e\n\x3c/div\x3e\n\x3c/noscript\x3e',2,'\n\n\x3cscript type\x3d\x22text/javascript\x22\x3evar google_conversion_id\x3d956542766,google_custom_params\x3dwindow.google_tag_params,google_remarketing_only\x3d!0;\x3c/script\x3e\n\x3cscript type\x3d\x22text/javascript\x22 src\x3d\x22//www.googleadservices.com/pagead/conversion.js\x22\x3e\x3c/script\x3e\n\x3cnoscript\x3e\n\x3cdiv style\x3d\x22display:inline;\x22\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22border-style:none;\x22 alt\x3d\x22\x22 src\x3d\x22//googleads.g.doubleclick.net/pagead/viewthroughconversion/956542766/?value\x3d0\x26amp;guid\x3dON\x26amp;script\x3d0\x22\x3e\n\x3c/div\x3e\n\x3c/noscript\x3e',4,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=ok(c,a);return b}());rk(dk,0,"3:0,3:1,6:2,0:3,1:4,3:6,8:7,5:8,7:9,11:10,9:11,3:12,4:13,9:14,4:15,9:16,4:17,10:7,9:18,3:19,6:20,6:21,2:22,6:23,2:24,3:25,6:26,6:27");rk(ek,1,"G,AAAG,AAAa,AAAiB,AAAAG,CAAAI");rk(gk,1,"Z");rk(Z,1,"gf,AhD,AhM,AhwB");rk(kh,2,"B:P::");rk(lh,4,"5.5.5.5:");for(var jl=0;jl<Z.length;jl++){var kl=Z[jl],ll=1;kl[ud]?ll=2:kl[Ie]&&(ll=0);Ka[jl]={firingOption:ll,state:void 0};La[jl]=[]}il.cb();
(function(a){})("async");
(function(){var a=J("dataLayer",[],!1),b=J("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};ua.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Gf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Kg.push.apply(Kg,b);300<this.length;)this.shift();return Tg()};Kg.push.apply(Kg,a.slice(0));r(Ug)})();
if("interactive"==Q.readyState&&!Q.createEventObject||"complete"==Q.readyState)sf();else{V(Q,"DOMContentLoaded",sf);V(Q,"readystatechange",sf);if(Q.createEventObject&&Q.documentElement.doScroll){var tl=!0;try{tl=!C.frameElement}catch(a){}tl&&uf()}V(C,"load",sf)}"complete"===Q.readyState?Hf():V(C,"load",Hf);
(function(a){})("async");(function(){})();var _vs="res_ts:1458683370688000,srv_cl:126101404,ds:live,cv:4";
})()
