window.hjSiteSettings = window.hjSiteSettings || {"testers_widgets":[],"surveys":[],"heatmaps":[{"created_epoch_time":1467308184,"targeting":[{"negate":false,"pattern":"https:\/\/scotch.io\/","match_operation":"simple","component":"url"}],"id":618958}],"recording_capture_keystrokes":true,"polls":[{"persist_condition":"response","targeting":[{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"},{"negate":false,"pattern":"https:\/\/school.scotch.io\/enroll","match_operation":"simple","component":"url"}],"language":"en","created_epoch_time":1462223718,"targeting_percentage":100,"display_condition":"abandon","content":{"thankyou":"Thanks! Your feedback is highly appreciated!","questions":[{"nextByAnswer":[],"text":"If you didn't sign up for Scotch School early enrollment, what was it that stopped you?","labels":null,"answers":null,"next":"byOrder","type":"single-open-ended-multiple-line","randomize_answer_order":false}]},"effective_show_branding":true,"background":"#444","skin":"dark","position":"right","display_delay":0,"id":42530}],"site_id":201487,"record_targeting_rules":[{"negate":false,"pattern":"https:\/\/scotch.io\/","match_operation":"simple","component":"url"}],"forms":[{"field_info":[{"field_type":"radio","match_value":"3-month-promo","id":399072,"match_attribute":"id"},{"field_type":"radio","match_value":"6-month-promo","id":399073,"match_attribute":"id"},{"field_type":"radio","match_value":"year-promo","id":399074,"match_attribute":"id"},{"field_type":"email","match_value":"email","id":399075,"match_attribute":"name"},{"field_type":"password","match_value":"password","id":399076,"match_attribute":"id"}],"targeting":[{"negate":false,"pattern":"https:\/\/school.scotch.io\/","match_operation":"simple","component":"url"}],"selector_type":"id","created_epoch_time":1462198704,"selector":"stripe-form","id":40080}],"record":true,"r":0.2740667477,"deferred_page_contents":[]};

window.hjBootstrap = window.hjBootstrap || function (scriptUrl) {
    var s = document.createElement('script');
    s.src = scriptUrl;
    document.getElementsByTagName('head')[0].appendChild(s);
    window.hjBootstrap = function() {};
};

hjBootstrap('https://script.hotjar.com/modules-ff53d42a4d7f100201c6e78983209c2f.js');